name = "doqr"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "qr"
database_id = "eb21ee22-cea6-4dfb-bf33-2bcfef13426a"

